#!/bin/sh
set -e

# Runtime config is generated by a Python emitter that uses yaml.safe_dump,
# so secrets and operator-supplied values never reach the YAML parser via
# textual substitution. See borgmatic/emit_runtime_config.py for the rules.
# The emitter exits non-zero on a malformed .env value. Under `set -e` that
# would end the container silently, which is the one outcome the failure token
# exists to prevent — the config that borgmatic cannot run is exactly the case
# the entrypoint fallback below claims to cover, and it never gets that far.
if ! python3 /etc/borgmatic.d/emit_runtime_config.py; then
    echo "EPICURRENTS_BACKUP_FAILURE runtime config generation failed; no backups will run" >&2
    exit 1
fi

echo "Starting borgmatic — interval ${BACKUP_INTERVAL:-86400}s"
while true; do
    # The failure token matches the one borgmatic's own `after: error` hook
    # emits (FAILURE_TOKEN in emit_runtime_config.py), so a single log rule
    # catches both. This branch is not redundant with that hook: it also fires
    # when borgmatic never gets far enough to run hooks at all — an unparseable
    # config, a missing repository, a failure to reach the remote.
    borgmatic --config /run/borgmatic-active --stats \
        || echo "EPICURRENTS_BACKUP_FAILURE borgmatic exited with status $?" >&2
    sleep "${BACKUP_INTERVAL:-86400}"
done
