# Generated by Django 6.0.8 on 2026-09-03 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_path", models.CharField(max_length=2048)),
                ("pipeline_label", models.CharField(default="import", max_length=64)),
                (
                    "structure",
                    models.CharField(
                        choices=[
                            ("recursive", "Recursive (mirror directory tree as Collections)"),
                            ("recursive_flat", "Recursive flat (scan subdirectories, no Collections)"),
                            ("flat", "Flat (top-level directory only)"),
                        ],
                        default="recursive",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "In Progress"), ("completed", "Completed"), ("aborted", "Aborted")],
                        db_index=True,
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recording",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original_name", models.CharField(max_length=255)),
                ("display_name", models.CharField(blank=True, default=None, max_length=255, null=True)),
                ("stored_name", models.CharField(max_length=255, unique=True)),
                ("file_extension", models.CharField(blank=True, default="", max_length=32)),
                ("file_size", models.BigIntegerField()),
                ("file_path", models.CharField(max_length=1024)),
                ("file_hash", models.CharField(blank=True, default="", max_length=64)),
                ("content_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("processing_error", models.TextField(blank=True, default="")),
                ("modality", models.CharField(blank=True, default="", max_length=32)),
                ("power_line_frequency", models.FloatField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportJobFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("relative_path", models.CharField(max_length=2048)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="files", to="recordings.importjob"
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_job_files",
                        to="recordings.recording",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecordingMeta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.CharField(max_length=255)),
                ("format", models.CharField(max_length=8)),
                ("duration", models.FloatField()),
                ("data_record_count", models.IntegerField()),
                ("data_record_duration", models.FloatField()),
                ("signal_count", models.IntegerField()),
                ("discontinuous", models.BooleanField(default=False)),
                ("recording_date", models.DateTimeField(blank=True, null=True)),
                (
                    "channel_layout",
                    models.CharField(
                        choices=[
                            ("referential", "Referential"),
                            ("bipolar", "Bipolar"),
                            ("mixed", "Mixed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("unresolved_channel_count", models.PositiveSmallIntegerField(default=0)),
                ("channel_order_version", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recording_metas",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SignalInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("index", models.PositiveSmallIntegerField()),
                ("label", models.CharField(max_length=64)),
                ("source_label", models.CharField(blank=True, default="", max_length=64)),
                ("source_transducer_type", models.CharField(blank=True, default="", max_length=160)),
                ("source_prefiltering", models.CharField(blank=True, default="", max_length=160)),
                ("source_index", models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ("canonical_label", models.CharField(blank=True, default="", max_length=32)),
                ("signal_type", models.CharField(blank=True, default="", max_length=32)),
                ("physical_unit", models.CharField(blank=True, default="", max_length=32)),
                ("transducer_type", models.CharField(blank=True, default="", max_length=160)),
                ("prefiltering", models.CharField(blank=True, default="", max_length=160)),
                ("physical_min", models.FloatField()),
                ("physical_max", models.FloatField()),
                ("digital_min", models.IntegerField()),
                ("digital_max", models.IntegerField()),
                ("units_per_bit", models.FloatField()),
                ("digital_offset", models.FloatField()),
                ("sample_count", models.PositiveIntegerField()),
                ("sampling_rate", models.FloatField()),
                ("highpass", models.FloatField(default=0.0)),
                ("lowpass", models.FloatField(default=0.0)),
                ("notch", models.FloatField(default=0.0)),
                ("is_annotation_channel", models.BooleanField(default=False)),
                (
                    "meta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="recordings.recordingmeta",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
            },
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(fields=["owner", "created_at"], name="recordings__owner_i_79269e_idx"),
        ),
        migrations.AddConstraint(
            model_name="importjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "in_progress")), fields=("status",), name="importjob_single_in_progress"
            ),
        ),
        migrations.AddIndex(
            model_name="recording",
            index=models.Index(fields=["author", "created_at"], name="recordings__author__d4464e_idx"),
        ),
        migrations.AddIndex(
            model_name="recording",
            index=models.Index(fields=["created_at"], name="recordings__created_a655dd_idx"),
        ),
        migrations.AddIndex(
            model_name="recording",
            index=models.Index(fields=["content_hash"], name="recordings__content_4a69c6_idx"),
        ),
        migrations.AddIndex(
            model_name="recording",
            index=models.Index(
                fields=["stored_name"], name="recording_stored_name_like", opclasses=["varchar_pattern_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="importjobfile",
            index=models.Index(fields=["job", "status"], name="recordings__job_id_5ff629_idx"),
        ),
        migrations.AddConstraint(
            model_name="importjobfile",
            constraint=models.UniqueConstraint(
                fields=("job", "relative_path"), name="importjobfile_unique_path_per_job"
            ),
        ),
        migrations.AddIndex(
            model_name="recordingmeta",
            index=models.Index(fields=["content_type", "object_id"], name="recordings__content_0f5d13_idx"),
        ),
        migrations.AddConstraint(
            model_name="recordingmeta",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id"), name="recordingmeta_unique_per_object"
            ),
        ),
        migrations.AddConstraint(
            model_name="signalinfo",
            constraint=models.UniqueConstraint(fields=("meta", "index"), name="signalinfo_unique_meta_index"),
        ),
    ]
