# Generated by Django 6.0.8 on 2026-09-28 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("recordings", "0002_recording_stored_hash"),
        ("recordings", "0003_recordingmeta_deidentification_record"),
        ("recordings", "0004_submission_batch"),
        ("recordings", "0005_recording_public_source"),
        ("recordings", "0006_merge_submission_batches"),
        ("recordings", "0007_submission_ledger"),
        ("recordings", "0008_submissionfile_failed_at"),
    ]

    dependencies = [
        ("library", "0002_release_gating_and_pools"),
        ("recordings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="public_source",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="recording",
            name="stored_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="recordingmeta",
            name="annotation_text_preserved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recordingmeta",
            name="deidentification_version",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SubmissionLedger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_hash", models.CharField(editable=False, max_length=32, unique=True)),
                ("ingested_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submission_ledgers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_ledgers",
                        to="library.dataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stored_name", models.CharField(max_length=255, unique=True)),
                ("file_extension", models.CharField(max_length=32)),
                ("file_path", models.CharField(max_length=1024)),
                ("file_size", models.BigIntegerField()),
                ("file_hash", models.CharField(max_length=64)),
                ("sidecar_hash", models.CharField(max_length=64)),
                ("sidecar", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("failed", "Failed")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ledger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="recordings.submissionledger",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="submissionledger",
            index=models.Index(fields=["dataset", "created_at"], name="recordings__dataset_8f664b_idx"),
        ),
        migrations.AddConstraint(
            model_name="submissionledger",
            constraint=models.UniqueConstraint(
                condition=models.Q(("contributor__isnull", False)),
                fields=("dataset", "contributor"),
                name="submission_ledger_one_per_contributor",
            ),
        ),
        migrations.AddIndex(
            model_name="submissionfile",
            index=models.Index(fields=["status", "received_at"], name="recordings__status_39f133_idx"),
        ),
    ]
