"""Add ``SubmissionBatch`` and ``SubmissionFile``: the validating submission path's batch target and spool rows."""

# Generated by Django 6.0.8 on 2026-09-23 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0004_dataset_submission_group"),
        ("recordings", "0003_recordingmeta_deidentification_record"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_hash", models.CharField(editable=False, max_length=32, unique=True)),
                ("profile_key", models.CharField(max_length=64)),
                ("ingested_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submission_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_batches",
                        to="library.dataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stored_name", models.CharField(max_length=255, unique=True)),
                ("file_extension", models.CharField(max_length=32)),
                ("file_path", models.CharField(max_length=1024)),
                ("file_size", models.BigIntegerField()),
                ("file_hash", models.CharField(max_length=64)),
                ("sidecar_hash", models.CharField(max_length=64)),
                ("sidecar", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("failed", "Failed")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="recordings.submissionbatch",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="submissionbatch",
            index=models.Index(fields=["dataset", "created_at"], name="recordings__dataset_8f664b_idx"),
        ),
        migrations.AddIndex(
            model_name="submissionfile",
            index=models.Index(fields=["status", "received_at"], name="recordings__status_39f133_idx"),
        ),
    ]
