"""Add ``Recording.public_source``: the DOI or URL of the published dataset a recording was taken from."""

# Generated by Django 6.0.8 on 2026-09-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recordings", "0004_submission_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="public_source",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
