/**
 * Platform-owned lead-field source for the viewer's source-localisation tool.
 *
 * The viewer knows nothing about where lead fields live — it asks for one through the
 * `LeadFieldProvider` the platform injects at `SETUP.modules.eeg.leadFieldProvider` (see
 * `src/viewer/base.ts`). Every URL, credential and fallback decision therefore lives here, in the
 * consumer that owns those URLs, rather than being hard-coded into the viewer submodule.
 *
 * Two sources, tried in order:
 *
 * 1. The static bundle under `/vendor/leadfields/`, generated by the compute app and served as
 *    plain files. Its `manifest.json` carries every field a client needs — section byte lengths,
 *    channel names, grid shape — so a hit costs one manifest fetch (memoised) plus the blob, with
 *    no metadata round-trip and no response headers to read. Being static, it is also cacheable by
 *    the service worker, which is the point of generating it.
 * 2. The compute API (`/compute/api/v1/eeg/leadfield/…`), which serves lead fields computed on
 *    demand and held in the database. Shape information arrives as `X-*` response headers here.
 *
 * A montage missing from both sources resolves to null — the tool renders that as "not available
 * on this server". A broken API lookup rejects, so the tool offers a retry instead of a dead end.
 */

import type { LeadFieldData, LeadFieldProvider } from '@epicurrents/interface/modules/eeg'

/** Location of the compute-generated static lead-field bundle. */
const MANIFEST_URL = '/vendor/leadfields/manifest.json'

/** One record of `manifest.json`, as written by `compute.eeg.leadfield_io.build_manifest_entry`. */
type LeadFieldManifestEntry = {
    montage_name:       string
    n_orient:           number
    grid_resolution_mm: number
    n_channels:         number
    n_sources:          number
    channel_names:      string[]
    /** Byte length of the lead-field section at the start of the blob. */
    lead_field_bytes:   number
    /** Byte length of the source-position section that follows it. */
    src_pos_bytes:      number
    /** Blob filename, content-hashed so a regenerated bundle never collides with a cached copy. */
    file:               string
    /** Blob location, relative to the manifest. */
    url:                string
}

type LeadFieldManifest = {
    entries:        LeadFieldManifestEntry[]
    format_version: number
}

/**
 * The parsed manifest, or null when the deployment ships no static bundle.
 *
 * Memoised as the promise rather than the value so concurrent first calls share one fetch. A
 * failed fetch resolves to null instead of rejecting: a missing bundle is not an error, it just
 * means every lookup goes to the API.
 */
let _manifest: Promise<LeadFieldManifest | null> | null = null

const loadManifest = (): Promise<LeadFieldManifest | null> => {
    _manifest ??= fetch(MANIFEST_URL, { credentials: 'same-origin' })
        .then((resp) => (resp.ok ? resp.json() as Promise<LeadFieldManifest> : null))
        .catch(() => null)
    return _manifest
}

/**
 * Split a lead-field blob into its two float64 sections.
 *
 * Both are views into the same `ArrayBuffer`, so the split itself copies nothing. `lfBytes` is a
 * whole number of float64s by construction, which keeps the second view's offset aligned.
 */
const sliceBlob = (buffer: ArrayBuffer, lfBytes: number, nSources: number): [Float64Array, Float64Array] => {
    if (buffer.byteLength < lfBytes + nSources*3*8) {
        throw new Error(
            `Lead field blob is truncated: got ${buffer.byteLength} bytes, `
            + `expected at least ${lfBytes + nSources*3*8}.`
        )
    }
    return [
        new Float64Array(buffer, 0, lfBytes/8),
        new Float64Array(buffer, lfBytes, nSources*3),
    ]
}

/**
 * Look the montage up in the static bundle.
 *
 * Resolves to null on any miss — no bundle, no matching entry, or an entry whose blob will not
 * download — so the API fallback always gets its turn. That last case is worth tolerating rather
 * than failing on: the service worker can hand back a manifest whose content-hashed blobs a
 * redeploy has since purged, and the API can still serve what the stale manifest cannot. It is
 * logged, because it also means the bundle needs regenerating.
 */
const fetchStatic = async (
    montageName: string,
    nOrient:     number,
    gridResMm:   number,
): Promise<LeadFieldData | null> => {
    const manifest = await loadManifest()
    const entry = manifest?.entries.find(
        (e) => e.montage_name === montageName
               && e.n_orient === nOrient
               && e.grid_resolution_mm === gridResMm
    )
    if (!entry) {
        return null
    }
    const url = new URL(entry.url, new URL(MANIFEST_URL, window.location.origin))
    try {
        const resp = await fetch(url, { credentials: 'same-origin' })
        if (!resp.ok) {
            throw new Error(`HTTP ${resp.status}`)
        }
        const [leadField, srcPos] = sliceBlob(await resp.arrayBuffer(), entry.lead_field_bytes, entry.n_sources)
        return {
            leadField,
            srcPos,
            nChannels:    entry.n_channels,
            nSources:     entry.n_sources,
            nOrient:      entry.n_orient,
            channelNames: entry.channel_names,
        }
    } catch (e) {
        console.warn(
            `[leadFields] Static lead field '${entry.file}' listed in the manifest could not be read `
            + `(${(e as Error).message}); falling back to the compute API.`
        )
        return null
    }
}

/**
 * Look the montage up through the compute API. Resolves to null when the API has nothing for this
 * caller, and rejects on any other failure.
 *
 * Three statuses mean "nothing here", not "broken". 404 is the plain miss: no lead field has been
 * computed for these parameters. 401 and 403 are the public viewer, which is auth-free by design
 * and can never reach these endpoints — treating those as failures would offer its users a retry
 * that cannot succeed, where the honest answer is that the montage is unavailable on this server.
 */
const fetchFromApi = async (
    montageName: string,
    nOrient:     number,
    gridResMm:   number,
): Promise<LeadFieldData | null> => {
    const query = `?n_orient=${nOrient}&grid_resolution_mm=${gridResMm}`
    const base  = `/compute/api/v1/eeg/leadfield/${encodeURIComponent(montageName)}/`
    // Metadata first: it carries the channel names, so a miss costs nothing beyond this request.
    const metaResp = await fetch(`${base}${query}`, { credentials: 'same-origin' })
    if (metaResp.status === 404 || metaResp.status === 401 || metaResp.status === 403) {
        return null
    }
    if (!metaResp.ok) {
        throw new Error(`Lead field metadata fetch failed: HTTP ${metaResp.status}.`)
    }
    const meta = await metaResp.json() as { channel_names: string[] }

    const dataResp = await fetch(`${base}data/${query}`, { credentials: 'same-origin' })
    if (!dataResp.ok) {
        throw new Error(`Lead field download failed: HTTP ${dataResp.status}.`)
    }
    const header = (name: string, fallback: number) => {
        const value = Number.parseInt(dataResp.headers.get(name) ?? '')
        return Number.isFinite(value) ? value : fallback
    }
    const lfBytes  = header('X-LeadField-Bytes', 0)
    const nSources = header('X-N-Sources', 0)
    const [leadField, srcPos] = sliceBlob(await dataResp.arrayBuffer(), lfBytes, nSources)
    return {
        leadField,
        srcPos,
        nChannels:    header('X-N-Channels', meta.channel_names.length),
        nSources,
        nOrient:      header('X-N-Orient', 1),
        channelNames: meta.channel_names,
    }
}

/**
 * The provider handed to the EEG interface module: static bundle first, compute API second.
 *
 * The viewer memoises the result per (montage, nOrient, gridResMm) triple, so this runs once per
 * distinct lead field per session and needs no cache of its own beyond the manifest.
 */
export const leadFieldProvider: LeadFieldProvider = async (montageName, nOrient, gridResMm) =>
    await fetchStatic(montageName, nOrient, gridResMm)
    ?? await fetchFromApi(montageName, nOrient, gridResMm)
