# Generated by Django 6.0.8 on 2026-09-03 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("annotations", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("recordings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "input_version_id",
                    models.CharField(
                        help_text="Signal version scored (a RecordingJob.output_version_id or 'source'). String, not FK.",
                        max_length=64,
                    ),
                ),
                (
                    "produces_kind",
                    models.CharField(
                        help_text="Annotation kind this run emits (a token in the annotations AnnotationKind vocabulary).",
                        max_length=64,
                    ),
                ),
                (
                    "input_digest",
                    models.CharField(
                        help_text="Run-identity digest: folds in the version digest and the digests of any annotation sets consumed (retention §1.1).",
                        max_length=64,
                    ),
                ),
                ("image_digest", models.CharField(help_text="Detector container/model identity.", max_length=128)),
                (
                    "params",
                    models.JSONField(default=dict, help_text="Run parameters; folded into input_digest for identity."),
                ),
                (
                    "grid_s",
                    models.FloatField(
                        help_text="Segmentation grid size in seconds (analysis-execution §1). Not part of identity."
                    ),
                ),
                ("halo_s", models.FloatField(default=0.0, help_text="Context halo around each segment, seconds.")),
                (
                    "max_event_span_s",
                    models.FloatField(default=0.0, help_text="Longest event the detector may emit, seconds."),
                ),
                (
                    "locality",
                    models.CharField(
                        choices=[
                            ("window_independent", "Window-independent"),
                            ("local_context", "Local context"),
                            ("global", "Global"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reproducible",
                    models.BooleanField(
                        default=False,
                        help_text="Earned via the conformance oracle (analysis-execution §5), never declared.",
                    ),
                ),
                (
                    "conformance",
                    models.JSONField(blank=True, default=dict, help_text="Conformance verdict: {mode, pass, corpus}."),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_runs",
                        to="recordings.recording",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "index",
                    models.PositiveIntegerField(help_text="Segment position; contract-stable across re-fan-out."),
                ),
                ("start_s", models.FloatField()),
                ("end_s", models.FloatField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=8,
                    ),
                ),
                (
                    "skip_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Why SKIPPED (gap/flat/out-of-coverage); must be resegmentation-invariant (analysis-execution §5).",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="segments", to="compute.analysisrun"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtifactCacheEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "version_id",
                    models.CharField(
                        help_text="Manifest hash of the materialised version, or 'source' for the base version.",
                        max_length=64,
                    ),
                ),
                (
                    "reproducible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the bytes can be rebuilt from source + manifest; governs eviction cost, not identity.",
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Location of the materialised bytes; '' once evicted/purged.",
                        max_length=1024,
                    ),
                ),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("materialised", "Materialised"),
                            ("evicted", "Evicted"),
                            ("tombstoned", "Tombstoned"),
                            ("purged", "Purged"),
                        ],
                        db_index=True,
                        default="materialised",
                        max_length=12,
                    ),
                ),
                (
                    "pinned",
                    models.BooleanField(
                        default=False, help_text="Explicit retention pin (retention §2.2); protects from GC."
                    ),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(blank=True, help_text="LRU timestamp for cache eviction.", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact_cache_entries",
                        to="recordings.recording",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeadFieldCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "montage_name",
                    models.CharField(
                        help_text="MNE standard montage name, e.g. 'standard_1020', 'biosemi64'. Must be accepted by mne.channels.make_standard_montage().",
                        max_length=128,
                    ),
                ),
                (
                    "n_channels",
                    models.PositiveIntegerField(help_text="Number of EEG channels (rows of the lead field matrix)."),
                ),
                (
                    "n_sources",
                    models.PositiveIntegerField(help_text="Number of source grid points (columns ÷ n_orient)."),
                ),
                (
                    "n_orient",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Orientations per source: 1 = fixed (surface normal), 3 = free (x/y/z)."
                    ),
                ),
                ("grid_resolution_mm", models.FloatField(default=7.5, help_text="Source grid spacing in millimetres.")),
                (
                    "sphere_radius_m",
                    models.FloatField(default=0.09, help_text="Radius of the spherical head model in metres."),
                ),
                (
                    "sphere_center_m",
                    models.JSONField(
                        default=list, help_text="[x, y, z] centre of the sphere in metres (head coordinates)."
                    ),
                ),
                (
                    "channel_names",
                    models.JSONField(help_text="Ordered list of channel name strings matching the matrix rows."),
                ),
                (
                    "lead_field",
                    models.BinaryField(
                        help_text="Raw little-endian float64 bytes of the lead field matrix, shape (n_channels, n_sources * n_orient), C order."
                    ),
                ),
                (
                    "src_pos",
                    models.BinaryField(
                        help_text="Raw little-endian float64 bytes of the source positions, shape (n_sources, 3), C order, in metres."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [models.Index(fields=["montage_name"], name="compute_lfc_montage_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("montage_name", "n_orient", "grid_resolution_mm"),
                        name="compute_leadfieldcache_unique_montage_orient_res",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PipelineRunAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_object_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("reconstruct.ran", "Reconstruct ran"),
                            ("analysis.started", "Analysis started"),
                            ("analysis.finished", "Analysis finished"),
                            ("detector.egress", "Detector egress"),
                            ("artifact.evicted", "Artifact evicted"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-pipeline payload. NEVER clinical findings; NEVER unmasked PII.",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("prev_hash", models.CharField(blank=True, default="", max_length=32)),
                ("content_hash", models.CharField(blank=True, default="", max_length=32)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_run_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_run_audits",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecordingJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stage_name",
                    models.CharField(
                        help_text="Reconstruction stage identifier; matches the stage registry.", max_length=64
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Resolved topological position in the reconstruction chain."
                    ),
                ),
                ("enabled", models.BooleanField(default=True, help_text="Per-recording override to skip this stage.")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=8,
                    ),
                ),
                (
                    "input_digest",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hash of the bytes this stage consumed (signal-pipeline-plan §3.2 input_hash).",
                        max_length=64,
                    ),
                ),
                (
                    "output_version_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Manifest hash of the version this stage produced; '' until DONE.",
                        max_length=64,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconstruction_jobs",
                        to="recordings.recording",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunAnnotation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "segment_index",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Producing segment; null for run-global (GLOBAL locality) output.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="annotations.event"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_links",
                        to="compute.analysisrun",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(
                fields=["recording", "input_version_id", "produces_kind"], name="compute_arun_rec_ver_kind_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisrun",
            constraint=models.UniqueConstraint(
                fields=("input_digest", "image_digest"), name="compute_analysisrun_unique_run_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysissegment",
            constraint=models.UniqueConstraint(
                fields=("run", "index"), name="compute_analysissegment_unique_index_per_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactcacheentry",
            constraint=models.UniqueConstraint(
                fields=("recording", "version_id"), name="compute_artifactcache_unique_version_per_recording"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerunaudit",
            index=models.Index(fields=["target_content_type", "target_object_id"], name="compute_paudit_target_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelinerunaudit",
            index=models.Index(fields=["action", "created_at"], name="compute_paudit_action_dt_idx"),
        ),
        migrations.AddIndex(
            model_name="recordingjob",
            index=models.Index(fields=["recording", "order"], name="compute_recjob_rec_order_idx"),
        ),
        migrations.AddConstraint(
            model_name="recordingjob",
            constraint=models.UniqueConstraint(
                fields=("recording", "stage_name"), name="compute_recordingjob_unique_stage_per_recording"
            ),
        ),
        migrations.AddIndex(
            model_name="runannotation",
            index=models.Index(fields=["run", "segment_index"], name="compute_runann_run_segment_idx"),
        ),
        migrations.AddIndex(
            model_name="runannotation",
            index=models.Index(fields=["event"], name="compute_runann_event_idx"),
        ),
        migrations.AddConstraint(
            model_name="runannotation",
            constraint=models.UniqueConstraint(
                fields=("run", "event"), name="compute_runannotation_unique_event_per_run"
            ),
        ),
    ]
