# Generated by Django 6.0.8 on 2026-09-03 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "interface",
                    models.CharField(
                        choices=[("api", "API"), ("celery", "Celery"), ("command", "Command")],
                        db_index=True,
                        default="api",
                        max_length=16,
                    ),
                ),
                ("verb", models.CharField(max_length=128)),
                ("method", models.CharField(blank=True, default="", max_length=12)),
                ("path", models.TextField(blank=True, default="")),
                ("status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("target_object_id", models.CharField(blank=True, default="", max_length=255)),
                ("target_identifier", models.TextField(blank=True, default="")),
                ("project", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_targets",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObjectChangeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.CharField(max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("modify", "Modify"),
                            ("delete", "Delete"),
                            ("rollback", "Rollback"),
                            ("erase", "Erase"),
                        ],
                        max_length=16,
                    ),
                ),
                ("project", models.CharField(blank=True, default="", max_length=64)),
                ("before_state", models.JSONField(default=dict)),
                ("changes", models.JSONField(blank=True, null=True)),
                ("after_hash", models.CharField(max_length=32)),
                ("hash_algorithm", models.CharField(default="v1", max_length=8)),
                ("hash_key_version", models.IntegerField(blank=True, null=True)),
                ("prev_hash", models.CharField(blank=True, default="", max_length=32)),
                ("sequence_no", models.BigIntegerField(blank=True, null=True)),
                ("extra_payload", models.JSONField(blank=True, default=dict)),
                ("erased_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("erased_hash", models.CharField(blank=True, default="", max_length=32)),
                ("erased_hash_algorithm", models.CharField(blank=True, default="", max_length=8)),
                ("erased_hash_key_version", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="activity.activity",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="object_change_logs",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_object_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["created_at"], name="activity_ac_created_6c38cf_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["verb", "created_at"], name="activity_ac_verb_f0611d_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["target_content_type", "target_object_id"], name="activity_ac_target__d2ae16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="objectchangelog",
            index=models.Index(fields=["created_at"], name="activity_ob_created_4b9c46_idx"),
        ),
        migrations.AddIndex(
            model_name="objectchangelog",
            index=models.Index(
                fields=["content_type", "object_id", "created_at"], name="activity_ob_content_3f603e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="objectchangelog",
            index=models.Index(fields=["action", "created_at"], name="activity_ob_action_779752_idx"),
        ),
        migrations.AddIndex(
            model_name="objectchangelog",
            index=models.Index(fields=["content_type", "sequence_no"], name="activity_ob_content_baf071_idx"),
        ),
    ]
