# Generated by Django 6.0.8 on 2026-09-03 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FederatedPeer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(max_length=512, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("public_key", models.CharField(max_length=64)),
                ("public_key_next", models.CharField(blank=True, default="", max_length=64)),
                ("public_key_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("is_trusted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_federated_peers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FederationAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("peer_url", models.CharField(max_length=512)),
                ("remote_user_id", models.CharField(max_length=512)),
                ("action", models.CharField(max_length=64)),
                ("target_object_id", models.CharField(blank=True, default="", max_length=255)),
                ("status_code", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "peer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="federation.federatedpeer",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="federation_audit_logs",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["peer", "-created_at"], name="federation__peer_id_c38c62_idx"),
                    models.Index(
                        fields=["target_content_type", "target_object_id", "-created_at"],
                        name="federation__target__4f33d2_idx",
                    ),
                ],
            },
        ),
    ]
