# Generated by Django 6.0.8 on 2026-09-03 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DicomStudy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("study_instance_uid", models.CharField(db_index=True, max_length=64)),
                ("study_date", models.CharField(blank=True, default="", max_length=8)),
                ("study_time", models.CharField(blank=True, default="", max_length=16)),
                ("study_description", models.CharField(blank=True, default="", max_length=256)),
                ("patient_name", models.CharField(blank=True, default="", max_length=256)),
                ("patient_id", models.CharField(blank=True, default="", max_length=64)),
                ("patient_birth_date", models.CharField(blank=True, default="", max_length=8)),
                ("patient_sex", models.CharField(blank=True, default="", max_length=16)),
                ("patient_age", models.CharField(blank=True, default="", max_length=4)),
                ("accession_number", models.CharField(blank=True, default="", max_length=64)),
                ("num_instances", models.IntegerField(default=0)),
                ("modalities", models.CharField(blank=True, default="", max_length=256)),
                ("content_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("attachment_object_id", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                (
                    "attachment_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dicom_study_attachments_by_type",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dicom_studies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "DICOM studies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DicomSeries",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("series_instance_uid", models.CharField(db_index=True, max_length=64)),
                ("series_description", models.CharField(blank=True, default="", max_length=256)),
                ("series_number", models.CharField(blank=True, default="", max_length=12)),
                ("series_date", models.CharField(blank=True, default="", max_length=8)),
                ("modality", models.CharField(blank=True, default="", max_length=16)),
                ("slice_thickness", models.CharField(blank=True, default="", max_length=16)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="series", to="dicom.dicomstudy"
                    ),
                ),
            ],
            options={
                "ordering": ["series_number", "series_instance_uid"],
            },
        ),
        migrations.CreateModel(
            name="DicomInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sop_instance_uid", models.CharField(db_index=True, max_length=64)),
                ("sop_class_uid", models.CharField(blank=True, default="", max_length=64)),
                ("instance_number", models.CharField(blank=True, default="", max_length=12)),
                ("columns", models.IntegerField(blank=True, null=True)),
                ("rows", models.IntegerField(blank=True, null=True)),
                ("photometric_interpretation", models.CharField(blank=True, default="", max_length=16)),
                ("bits_allocated", models.IntegerField(blank=True, null=True)),
                ("bits_stored", models.IntegerField(blank=True, null=True)),
                ("pixel_representation", models.IntegerField(blank=True, null=True)),
                ("samples_per_pixel", models.IntegerField(blank=True, null=True)),
                ("high_bit", models.IntegerField(blank=True, null=True)),
                ("number_of_frames", models.IntegerField(blank=True, null=True)),
                ("pixel_spacing", models.JSONField(blank=True, null=True)),
                ("image_orientation_patient", models.JSONField(blank=True, null=True)),
                ("image_position_patient", models.JSONField(blank=True, null=True)),
                ("image_type", models.JSONField(blank=True, null=True)),
                ("frame_of_reference_uid", models.CharField(blank=True, default="", max_length=64)),
                ("window_center", models.CharField(blank=True, default="", max_length=32)),
                ("window_width", models.CharField(blank=True, default="", max_length=32)),
                ("stored_name", models.CharField(max_length=255, unique=True)),
                ("file_size", models.BigIntegerField()),
                ("file_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("ready", "Ready"), ("failed", "Failed")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="instances", to="dicom.dicomseries"
                    ),
                ),
            ],
            options={
                "ordering": ["instance_number", "sop_instance_uid"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("series", "sop_instance_uid"), name="dicominstance_unique_sop_per_series"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="dicomstudy",
            index=models.Index(
                fields=["attachment_content_type", "attachment_object_id"], name="dicom_attachment_lookup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dicomstudy",
            constraint=models.UniqueConstraint(
                fields=("author", "study_instance_uid"), name="dicomstudy_unique_uid_per_author"
            ),
        ),
        migrations.AddConstraint(
            model_name="dicomseries",
            constraint=models.UniqueConstraint(
                fields=("study", "series_instance_uid"), name="dicomseries_unique_uid_per_study"
            ),
        ),
    ]
