# Generated by Django 6.0.8 on 2026-09-27 12:54

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenancePackage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("version", models.CharField(max_length=32)),
                ("project", models.CharField(blank=True, max_length=64)),
                ("plugins", models.JSONField(blank=True, default=list)),
                ("platform_compatible", models.CharField(blank=True, max_length=64)),
                ("built_at", models.DateTimeField(blank=True, null=True)),
                ("size", models.BigIntegerField(default=0)),
                ("key_id", models.CharField(blank=True, max_length=16)),
                ("manifest", models.JSONField(blank=True, default=dict)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unverified", "Unverified"),
                            ("invalid", "Invalid"),
                            ("applied", "Applied"),
                            ("pruned", "Pruned"),
                        ],
                        default="available",
                        max_length=16,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("operation", models.CharField(max_length=100)),
                ("executor", models.CharField(choices=[("celery", "Celery"), ("host", "Host agent")], max_length=8)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("accepted", "Accepted"),
                            ("running", "Running"),
                            ("awaiting_verification", "Awaiting verification"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("rolling_back", "Rolling back"),
                            ("rolled_back", "Rolled back"),
                            ("rollback_failed", "Rollback failed"),
                        ],
                        default="requested",
                        max_length=32,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=64)),
                ("step", models.CharField(blank=True, max_length=64)),
                ("in_flight", models.BooleanField(default=True)),
                ("args", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("verify_deadline", models.DateTimeField(blank=True, null=True)),
                ("verify_requested_at", models.DateTimeField(blank=True, null=True)),
                ("rollback_requested_at", models.DateTimeField(blank=True, null=True)),
                ("spool_updated_at", models.DateTimeField(blank=True, null=True)),
                ("output", models.TextField(blank=True)),
                ("agent_version", models.CharField(blank=True, max_length=32)),
                ("installed_version_before", models.CharField(blank=True, max_length=32)),
                ("target_version", models.CharField(blank=True, max_length=32)),
                ("running_version", models.CharField(blank=True, max_length=32)),
                ("snapshot", models.CharField(blank=True, max_length=128)),
                ("post_snapshot", models.CharField(blank=True, max_length=128)),
                ("migrations_applied", models.BooleanField(blank=True, null=True)),
                ("last_notified_state", models.CharField(blank=True, max_length=32)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="maintenance.maintenancepackage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("in_flight", True)),
                        fields=("in_flight",),
                        name="maintenance_one_job_in_flight",
                    )
                ],
            },
        ),
    ]
