# Generated by Django 6.0.8 on 2026-09-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancejob",
            name="migrations_applied",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
