# Generated by Django 6.0.8 on 2026-09-03 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("federation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewerConfigOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project", models.CharField(max_length=64, unique=True)),
                ("overrides", models.JSONField(blank=True, default=dict)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AccessRight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.CharField(max_length=255)),
                ("public_share_token", models.CharField(blank=True, max_length=128, null=True, unique=True)),
                (
                    "remote_user_id",
                    models.CharField(
                        blank=True,
                        help_text="Remote user identifier (JWT 'sub') on the federated peer. Blank = any user from that peer.",
                        max_length=512,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("can_read", models.BooleanField(default=True)),
                ("can_write", models.BooleanField(default=False)),
                ("can_share", models.BooleanField(default=False)),
                (
                    "apply_middleware",
                    models.BooleanField(
                        default=False,
                        help_text="Pipe EDF/BDF file content through the configured middleware pipeline when serving this access right. Has no effect on non-EDF files or when the caller is the recording author or a superuser.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "access_giver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="granted_access_rights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "access_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_access_rights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "access_target_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_access_rights",
                        to="auth.group",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rights",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "federated_peer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rights",
                        to="federation.federatedpeer",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["content_type", "object_id"], name="epicurrents_content_1c6735_idx"),
                    models.Index(
                        fields=["access_target", "content_type", "object_id"], name="epicurrents_access__55f27b_idx"
                    ),
                    models.Index(
                        fields=["access_target_group", "content_type", "object_id"],
                        name="epicurrents_access__2acce9_idx",
                    ),
                    models.Index(
                        fields=["public_share_token", "content_type", "object_id"],
                        name="epicurrents_public__1c52af_idx",
                    ),
                    models.Index(
                        fields=["federated_peer", "content_type", "object_id"], name="epicurrents_federat_438fe2_idx"
                    ),
                    models.Index(fields=["expires_at"], name="epicurrents_expires_8aad24_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("can_read", True), ("can_write", True), ("can_share", True), _connector="OR"
                        ),
                        name="access_right_requires_some_permission",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("access_target__isnull", False),
                                ("access_target_group__isnull", True),
                                ("federated_peer__isnull", True),
                                ("public_share_token__isnull", True),
                            ),
                            models.Q(
                                ("access_target__isnull", True),
                                ("access_target_group__isnull", False),
                                ("federated_peer__isnull", True),
                                ("public_share_token__isnull", True),
                            ),
                            models.Q(
                                ("access_target__isnull", True),
                                ("access_target_group__isnull", True),
                                ("federated_peer__isnull", True),
                                ("public_share_token__isnull", False),
                            ),
                            models.Q(
                                ("access_target__isnull", True),
                                ("access_target_group__isnull", True),
                                ("federated_peer__isnull", False),
                                ("public_share_token__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="access_right_exactly_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("access_target__isnull", False)),
                        fields=("content_type", "object_id", "access_target"),
                        name="access_right_unique_user_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("access_target_group__isnull", False)),
                        fields=("content_type", "object_id", "access_target_group"),
                        name="access_right_unique_group_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("federated_peer__isnull", False)),
                        fields=("content_type", "object_id", "federated_peer", "remote_user_id"),
                        name="access_right_unique_federated_target",
                    ),
                ],
            },
        ),
    ]
