# Generated by Django 6.0.8 on 2026-09-28 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("epicurrents", "0002_alter_accessright_apply_middleware"),
        ("epicurrents", "0003_accessright_assessment"),
    ]

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("epicurrents", "0001_initial"),
        ("federation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accessright",
            name="assessment_date",
            field=models.DateField(
                blank=True,
                help_text="Date the assessment named by assessment_reference was made or last re-run.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accessright",
            name="assessment_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reference to the sharer's documented contextual assessment for this grant (an identifier or a URL), where one exists. Set together with assessment_date.",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="accessright",
            name="apply_middleware",
            field=models.BooleanField(
                default=True,
                help_text="Pipe EDF/BDF file content through the configured middleware pipeline when serving this access right. An explicit False grants the raw file. Has no effect on non-EDF files or when the caller is the recording author or a superuser.",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessright",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("assessment_date__isnull", True), ("assessment_reference", "")),
                    models.Q(models.Q(("assessment_reference", ""), _negated=True), ("assessment_date__isnull", False)),
                    _connector="OR",
                ),
                name="access_right_assessment_dated",
            ),
        ),
    ]
