#!/usr/bin/env bash
# build_ohif.sh — Build the OHIF viewer for the *dicom* plugin.
#
# Usage:
#   ./scripts/build_ohif.sh [--clean]
#
# What it does:
#   1. Ensures the ohif-viewer submodule is initialised and up to date.
#   2. Installs OHIF's Node dependencies (yarn is required; install via
#      `npm install -g yarn` if absent).
#   3. Writes a minimal app-config.js that points OHIF at the platform's
#      /plugin/dicom/api/v1/dicom/ endpoints.
#   4. Runs `yarn build` in ohif-viewer/platform/app/.
#   5. Copies the output to plugins/dicom/ohif-dist/ (served by Django).
#
# Environment variables:
#   OHIF_APP_CONFIG   Path to a custom app-config.js.  Defaults to the
#                     auto-generated config written by this script.
#   DICOM_API_BASE    Base URL for the platform API.  Defaults to an empty
#                     string (same-origin), which works when Django and the
#                     browser share an origin.
#
# Prerequisites:
#   - git (with submodule support)
#   - Node.js ≥ 18
#   - yarn (classic or berry — OHIF uses yarn workspaces)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OHIF_DIR="$REPO_ROOT/plugins/dicom/ohif-viewer"
DIST_DIR="$REPO_ROOT/plugins/dicom/ohif-dist"
APP_DIR="$OHIF_DIR/platform/app"

DICOM_API_BASE="${DICOM_API_BASE:-}"

# ------------------------------------------------------------------
# 1. Submodule
# ------------------------------------------------------------------
echo "==> Initialising OHIF submodule…"
cd "$REPO_ROOT"
# --checkout is required: the submodule is registered with `update = none` in
# .gitmodules (so default clones skip it), which a plain `submodule update`
# silently honours by doing nothing.
git submodule update --init --checkout --recursive plugins/dicom/ohif-viewer

# ------------------------------------------------------------------
# 2. App config
# ------------------------------------------------------------------
CONFIG_PATH="${OHIF_APP_CONFIG:-$APP_DIR/public/app-config.js}"
echo "==> Writing app-config.js to $CONFIG_PATH…"

cat > "$CONFIG_PATH" << EOF
/** Auto-generated by scripts/build_ohif.sh — do not edit by hand. */
window.config = {
  routerBasename: '/plugin/dicom/viewer',
  extensions: [],
  modes: [],
  defaultDataSourceName: 'dicomjson',
  dataSources: [
    {
      namespace: '@ohif/extension-default.dataSourcesModule.dicomjson',
      sourceName: 'dicomjson',
      configuration: {
        friendlyName: 'Epicurrents DICOM',
        // The viewer resolves this URL relative to the page origin.
        // It must point at the platform's ohif-json endpoint.
        // The study hash is substituted by the Vue plugin when opening the viewer.
        name: 'dicomjson',
      },
    },
    {
      namespace: '@ohif/extension-default.dataSourcesModule.wadouri',
      sourceName: 'dicomweb',
      configuration: {
        friendlyName: 'Epicurrents WADO-URI',
        wadoUriRoot: '${DICOM_API_BASE}/plugin/dicom/api/v1/dicom/wado/',
        imageRendering: 'wadors',
        thumbnailRendering: 'wadors',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: false,
        supportsWildcard: false,
      },
    },
  ],
  hotkeys: [],
};
EOF

# ------------------------------------------------------------------
# 3. Install dependencies
# ------------------------------------------------------------------
echo "==> Installing OHIF dependencies (this may take a few minutes)…"
cd "$OHIF_DIR"
yarn install --frozen-lockfile

# ------------------------------------------------------------------
# 4. Build
# ------------------------------------------------------------------
echo "==> Building OHIF viewer…"
cd "$APP_DIR"
yarn build

# ------------------------------------------------------------------
# 5. Copy dist
# ------------------------------------------------------------------
echo "==> Copying dist to $DIST_DIR…"
rm -rf "$DIST_DIR"
cp -r "$APP_DIR/dist" "$DIST_DIR"

echo ""
echo "✓ OHIF viewer built successfully."
echo "  Dist: $DIST_DIR"
echo "  Serve via: EPICURRENTS_PLUGINS=dicom python manage.py runserver"
echo "  Viewer URL: http://localhost:8000/plugin/dicom/viewer/"
