# Generated by Django 6.0.8 on 2026-09-03 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationKind",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "token",
                    models.CharField(
                        help_text="Semantic kind token, e.g. 'hypnogram', 'spike_events', 'artifact_spans'.",
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="token must be lowercase snake_case, e.g. 'spike_events'",
                                regex="^[a-z][a-z0-9_]*$",
                            )
                        ],
                    ),
                ),
                ("display_name", models.CharField(blank=True, default="", max_length=128)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["token"],
            },
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_object_id", models.CharField(max_length=255)),
                (
                    "version_id",
                    models.CharField(
                        db_default="source",
                        default="source",
                        help_text="Signal version this annotation is bound to; 'source' (base version) by default.",
                        max_length=64,
                    ),
                ),
                (
                    "object_hash",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="object_hash must be 32 alphanumeric characters", regex="^[A-Za-z0-9]{32}$"
                            )
                        ],
                    ),
                ),
                ("content_hash", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("content", models.JSONField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_targeted",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["author", "created_at"], name="annotations_author__dd7c36_idx"),
                    models.Index(
                        fields=["target_content_type", "target_object_id", "author", "created_at"],
                        name="annotations_target__6bff6d_idx",
                    ),
                    models.Index(fields=["content_hash"], name="annotations_content_818cda_idx"),
                    models.Index(fields=["object_hash"], name="annotations_object__920df9_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_content_type", "target_object_id", "version_id", "object_hash"),
                        name="annotation_unique_hash_per_target",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Code",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.CharField(max_length=255)),
                ("standard", models.CharField(max_length=64)),
                ("value", models.TextField()),
                ("meta", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_codes",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["content_type", "object_id"], name="annotations_content_eafb38_idx"),
                    models.Index(fields=["standard"], name="annotations_standar_eeed62_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "standard"),
                        name="annotations_code_unique_per_target_standard",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_object_id", models.CharField(max_length=255)),
                (
                    "version_id",
                    models.CharField(
                        db_default="source",
                        default="source",
                        help_text="Signal version this annotation is bound to; 'source' (base version) by default.",
                        max_length=64,
                    ),
                ),
                (
                    "object_hash",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="object_hash must be 32 alphanumeric characters", regex="^[A-Za-z0-9]{32}$"
                            )
                        ],
                    ),
                ),
                ("content_hash", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.FloatField()),
                ("duration", models.FloatField(blank=True, null=True)),
                ("value", models.JSONField(blank=True, null=True)),
                ("event_class", models.CharField(blank=True, default="", max_length=64)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_targeted",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["author", "created_at"], name="annotations_author__a25248_idx"),
                    models.Index(
                        fields=["target_content_type", "target_object_id", "author", "created_at"],
                        name="annotations_target__501b1b_idx",
                    ),
                    models.Index(fields=["content_hash"], name="annotations_content_8a8a1d_idx"),
                    models.Index(fields=["object_hash"], name="annotations_object__f4fce0_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_content_type", "target_object_id", "version_id", "object_hash"),
                        name="event_unique_hash_per_target",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Interruption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_object_id", models.CharField(max_length=255)),
                (
                    "version_id",
                    models.CharField(
                        db_default="source",
                        default="source",
                        help_text="Signal version this annotation is bound to; 'source' (base version) by default.",
                        max_length=64,
                    ),
                ),
                (
                    "object_hash",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="object_hash must be 32 alphanumeric characters", regex="^[A-Za-z0-9]{32}$"
                            )
                        ],
                    ),
                ),
                ("content_hash", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.FloatField()),
                ("duration", models.FloatField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_targeted",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["author", "created_at"], name="annotations_author__0e9692_idx"),
                    models.Index(
                        fields=["target_content_type", "target_object_id", "author", "created_at"],
                        name="annotations_target__0969ca_idx",
                    ),
                    models.Index(fields=["content_hash"], name="annotations_content_1f36d1_idx"),
                    models.Index(fields=["object_hash"], name="annotations_object__9b2bb6_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_content_type", "target_object_id", "version_id", "object_hash"),
                        name="interruption_unique_hash_per_target",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_object_id", models.CharField(max_length=255)),
                (
                    "version_id",
                    models.CharField(
                        db_default="source",
                        default="source",
                        help_text="Signal version this annotation is bound to; 'source' (base version) by default.",
                        max_length=64,
                    ),
                ),
                (
                    "object_hash",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="object_hash must be 32 alphanumeric characters", regex="^[A-Za-z0-9]{32}$"
                            )
                        ],
                    ),
                ),
                ("content_hash", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("value", models.JSONField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_targeted",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["author", "created_at"], name="annotations_author__cb7c1f_idx"),
                    models.Index(
                        fields=["target_content_type", "target_object_id", "author", "created_at"],
                        name="annotations_target__01d827_idx",
                    ),
                    models.Index(fields=["content_hash"], name="annotations_content_7bcee6_idx"),
                    models.Index(fields=["object_hash"], name="annotations_object__c8a0d6_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_content_type", "target_object_id", "version_id", "object_hash"),
                        name="label_unique_hash_per_target",
                    )
                ],
            },
        ),
    ]
