# Generated by Django 6.0.8 on 2026-09-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_self_asserted",
            field=models.BooleanField(default=False),
        ),
    ]
