# Generated by Django 6.0.8 on 2026-09-03 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "media_type",
                    models.CharField(
                        choices=[("document", "Document"), ("video", "Video")], db_index=True, max_length=16
                    ),
                ),
                ("attachment_object_id", models.CharField(blank=True, default="", max_length=255)),
                ("time_offset", models.FloatField(blank=True, default=None, null=True)),
                ("original_name", models.CharField(max_length=255)),
                ("display_name", models.CharField(blank=True, default=None, max_length=255, null=True)),
                ("stored_name", models.CharField(max_length=255, unique=True)),
                ("file_extension", models.CharField(blank=True, default="", max_length=32)),
                ("file_size", models.BigIntegerField()),
                ("file_path", models.CharField(max_length=1024)),
                ("file_hash", models.CharField(blank=True, default="", max_length=64)),
                ("content_hash", models.CharField(blank=True, default="", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                (
                    "attachment_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_attachments_by_type",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["author", "created_at"], name="media_media_author__a6c0a4_idx"),
                    models.Index(fields=["created_at"], name="media_media_created_74471a_idx"),
                    models.Index(fields=["content_hash"], name="media_media_content_fa0ca4_idx"),
                    models.Index(
                        fields=["attachment_content_type", "attachment_object_id"], name="media_attachment_lookup_idx"
                    ),
                ],
            },
        ),
    ]
