"""Contract tests for a project's own Python dependencies.

A project lives in its own repository and may need packages the platform does
not. It declares them in ``projects/<name>/requirements.txt`` and ships a lock
beside it, which the Dockerfile installs as a further ``pip install``.

The hazard is that the two closures overlap and pip does not mind. ``numpy`` is
in the platform's lock and in any project doing array work; ``matplotlib`` and
``platformdirs`` arrive transitively in both. A second ``--require-hashes``
install naming a different version of one of those does not conflict — it
succeeds, replaces what the platform lock pinned, and reports nothing. The
resulting image runs a version no lock was audited against, with every hash
check passing on the way in.

``scripts/lock-requirements.sh --project`` closes that by resolving the project
against the platform lock's exact versions as constraints, and stamping the
digest of those constraints into the project lock so a later platform relock is
detectable rather than silent. That guard lives in a shell script that needs
docker and a network, so it runs where those exist. These tests assert the same
invariants against the committed files, in the fast test job, and would catch a
project lock hand-edited or generated by some other means.

Static rather than a build for the same reason as test_image_targets: what
regresses is the wiring, and a real build takes minutes and a daemon. The
install itself was exercised by hand when this landed — an image built with
EPICURRENTS_PROJECT=<name> imports the project's extra packages at the locked versions with
numpy still at the platform's, and one built without the argument raises
ModuleNotFoundError on both while keeping mne, scipy and numpy.
"""

import hashlib
import re
from pathlib import Path

import pytest
import yaml
from django.conf import settings

from epicurrents.tests.test_image_targets import _pip_commands, _services, _stages

REPO = Path(settings.BASE_DIR)
PLATFORM_LOCK = REPO / "requirements.lock"
PROJECTS = REPO / "projects"

# The marker scripts/lock-requirements.sh writes into a project lock, recording
# which platform versions it was resolved against.
PINS_MARKER = "# platform-versions: "


def _pins(text: str) -> dict[str, set[str]]:
    """Map distribution name to the set of versions pinned for it.

    A set rather than a single version, because ``uv --universal`` resolves
    across platforms and may pin one package at two versions under different
    environment markers. Keeping the last match would drop one of them, and a
    disagreement on the dropped one would read as agreement.
    """
    pins: dict[str, set[str]] = {}
    for line in text.splitlines():
        match = re.match(r"^([A-Za-z0-9._-]+)==([^ \\;]+)", line)
        if match:
            pins.setdefault(re.sub(r"[-_.]+", "-", match.group(1)).lower(), set()).add(match.group(2))
    return pins


def _platform_constraints_digest() -> str:
    """The digest lock-requirements.sh stamps into a project lock.

    Reproduces the shell pipeline that derives the constraints file: strip the
    trailing hash continuation from each line, keep the version pins, hash the
    result. Deriving it rather than reading it back is the point — a test that
    read the stored value and compared it to itself would pass on any lock.
    """
    kept = []
    for line in PLATFORM_LOCK.read_text().splitlines():
        line = re.sub(r"[ \t]*\\$", "", line)
        if re.match(r"^[a-zA-Z0-9._-]+==", line):
            kept.append(line)
    return hashlib.sha256("".join(f"{line}\n" for line in kept).encode()).hexdigest()


def _project_dirs() -> list[Path]:
    return sorted(p for p in PROJECTS.iterdir() if p.is_dir() and not p.name.startswith("__"))


def _projects_with_requirements() -> list[Path]:
    return [p for p in _project_dirs() if (p / "requirements.txt").exists()]


class TestProjectLockIntegrity:
    def test_every_project_declaring_requirements_ships_a_lock(self):
        """The Dockerfile fails the build on a missing lock rather than
        installing the unpinned requirements, so this is the same finding
        arriving minutes earlier and without a daemon."""
        missing = [p.name for p in _projects_with_requirements() if not (p / "requirements.lock").exists()]
        assert not missing, (
            f"projects with requirements.txt and no requirements.lock: {missing} — "
            "run scripts/lock-requirements.sh --project <name> and commit the result"
        )

    @pytest.mark.parametrize("project", [p.name for p in _projects_with_requirements()])
    def test_shared_packages_pin_the_same_version(self, project):
        """The invariant the constrained resolution exists to produce, asserted
        directly rather than through the mechanism that produces it.

        A disagreement here is not a conflict anyone will be told about: pip
        installs the platform lock, then installs the project lock over it, and
        the second version wins silently.

        Stated as a subset rather than an equality, so it holds when a lock
        pins one package at two versions under different markers: the project
        may name fewer of them, but never a version the platform does not pin.
        """
        platform = _pins(PLATFORM_LOCK.read_text())
        project_pins = _pins((PROJECTS / project / "requirements.lock").read_text())
        disagreeing = {
            name: {"platform": sorted(platform[name]), "project": sorted(versions - platform[name])}
            for name, versions in project_pins.items()
            if name in platform and not versions <= platform[name]
        }
        assert not disagreeing, (
            f"{project} pins versions the platform lock does not, which its install "
            f"would silently put in place of the platform's: {disagreeing} — re-run "
            f"scripts/lock-requirements.sh --project {project}"
        )

    @pytest.mark.parametrize("project", [p.name for p in _projects_with_requirements()])
    def test_the_lock_records_the_platform_versions_it_was_resolved_against(self, project):
        """A project lock outlives the platform lock it was resolved against.
        Without the stamp, a platform relock leaves it looking fine while its
        install has started downgrading whatever moved.
        """
        text = (PROJECTS / project / "requirements.lock").read_text()
        stored = [line[len(PINS_MARKER) :].strip() for line in text.splitlines() if line.startswith(PINS_MARKER)]
        assert stored, f"{project}'s lock carries no {PINS_MARKER.strip()} line — regenerate it"
        assert stored[0] == _platform_constraints_digest(), (
            f"{project}'s lock was resolved against a different requirements.lock — re-run "
            f"scripts/lock-requirements.sh --project {project} and commit the result"
        )

    @pytest.mark.parametrize("project", [p.name for p in _projects_with_requirements()])
    def test_every_pinned_package_carries_a_hash(self, project):
        """One unhashed entry makes pip reject the whole file under
        --require-hashes, which fails the build — slowly, and at the wrong end
        of the pipeline."""
        joined = re.sub(r"\\\s*\n\s*", " ", (PROJECTS / project / "requirements.lock").read_text())
        unhashed = [
            line.split()[0]
            for line in joined.splitlines()
            if line.strip() and not line.strip().startswith("#") and "==" in line and "--hash=" not in line
        ]
        assert not unhashed, f"{project} lock entries without a hash: {unhashed}"


class TestDockerfileWiring:
    def test_the_project_requirements_stage_exists(self):
        assert "project-reqs" in _stages(), (
            "the stage that selects the active project's lock is gone, so a project's "
            "dependencies are no longer installed"
        )

    def test_the_project_lock_installs_separately_from_the_platform_lock(self):
        """--require-hashes applies to a whole pip invocation and the two locks
        are resolved separately, so they cannot share one command."""
        shared = [cmd for cmd in _pip_commands() if "project-requirements" in cmd and "-r requirements.lock" in cmd]
        assert not shared, f"the project lock shares a pip invocation with the platform lock: {shared}"

    def test_the_project_lock_is_installed_with_require_hashes(self):
        installs = [cmd for cmd in _pip_commands() if "project-requirements" in cmd]
        assert installs, "the Dockerfile never installs the project's lock"
        for command in installs:
            assert "--require-hashes" in command, f"the project lock's hashes are inert without the flag: {command}"

    def test_the_build_refuses_a_lock_resolved_against_a_different_platform_lock(self):
        """The build is the only place that holds both files, and the only guard
        a production deployment runs — the tests above execute in CI, which the
        project's own repository is not necessarily part of.

        Asserted as "the marker is compared in the same RUN that installs", not
        merely that the string appears somewhere: a mismatch check in a stage
        that never gates the install would satisfy a looser assertion while
        letting every mismatched lock through.
        """
        base = _stages()["base"]
        joined = re.sub(r"\\\s*\n\s*", " ", base)
        guarding = [
            line
            for line in joined.splitlines()
            if "project-requirements/requirements.lock" in line and PINS_MARKER.strip() in line
        ]
        assert guarding, (
            "the base stage installs the project's lock without comparing the platform-versions "
            "digest, so a project repository that has not caught up with a platform relock "
            "silently downgrades whatever moved"
        )
        assert "exit 1" in guarding[0], "the digest comparison does not fail the build"


class TestComposeWiring:
    def test_every_building_service_passes_the_active_project(self):
        """The build arg decides which project's lock the image installs. A
        service that missed it builds an image without the project's
        dependencies while its siblings have them, which surfaces as one
        container crash-looping on an import rather than as a build failure.
        """
        missing = [
            name
            for name, spec in _services().items()
            if isinstance(spec.get("build"), dict) and "EPICURRENTS_PROJECT" not in (spec["build"].get("args") or {})
        ]
        assert not missing, f"compose services build without EPICURRENTS_PROJECT: {missing}"

    def test_the_argument_is_interpolated_rather_than_hardcoded(self):
        """Read from the raw text, because the parsed value is whatever the
        environment interpolated at load time — including the developer's own
        .env, which would make a hardcoded project name look correct here.
        """
        source = (REPO / "docker-compose.yml").read_text()
        anchor = re.search(r"^x-build-args:\s*&build-args\n((?:\s+.+\n)+)", source, re.MULTILINE)
        assert anchor, "the shared build-args anchor is gone; each build block now has to be checked by hand"
        assert re.search(r"EPICURRENTS_PROJECT:\s*\$\{EPICURRENTS_PROJECT", anchor.group(1)), (
            "EPICURRENTS_PROJECT is not interpolated from the environment, so the image "
            "would be built for a project the stack does not run"
        )

    def test_the_production_overlay_does_not_drop_the_build_arguments(self):
        """The overlay replaces several keys outright with !override. Doing that
        to `build` would leave production building the base platform's image
        while development built the project's.
        """
        overlay = yaml.load((REPO / "docker-compose.prod.yml").read_text(), Loader=_TolerantLoader)
        for name, spec in (overlay.get("services") or {}).items():
            build = spec.get("build")
            if isinstance(build, dict):
                assert "EPICURRENTS_PROJECT" in (build.get("args") or {}), (
                    f"{name} redefines build in the production overlay without the project argument"
                )


class _TolerantLoader(yaml.SafeLoader):
    """Compose carries custom tags (``!override``) that SafeLoader rejects."""


def _ignore_tag(loader, suffix, node):
    if isinstance(node, yaml.SequenceNode):
        return loader.construct_sequence(node, deep=True)
    if isinstance(node, yaml.MappingNode):
        return loader.construct_mapping(node, deep=True)
    return loader.construct_scalar(node)


_TolerantLoader.add_multi_constructor("!", _ignore_tag)


class TestFrontendBuildSeesTheProject:
    """The build container has to hold the repository's layout, not just frontend/.

    A project's Vue plugin lives at ``projects/<name>/frontend/``, a sibling of
    ``frontend/``. The ``#project`` alias resolves ``../projects/...`` and each
    project's package.json reaches back with ``../../../frontend/*``, so the two
    only agree when they sit beside each other under one parent.

    Mounting ``./frontend`` alone — which is what the service did until a
    from-scratch build was attempted — leaves ``../projects`` outside the
    container entirely, and every project build fails on an alias pointing at a
    path that is not there. Nothing catches it on a developer machine, where the
    frontend is built on the host.
    """

    def _frontend_build(self):
        service = _services().get("frontend-build")
        assert service, "the frontend-build service is gone"
        return service

    def test_both_halves_of_the_repository_are_mounted(self):
        mounts = [m.split(":")[1] for m in self._frontend_build()["volumes"] if m.startswith("./")]
        assert any(m.endswith("/frontend") for m in mounts), "the platform frontend is not mounted"
        assert any(m.endswith("/projects") for m in mounts), (
            "projects/ is not mounted, so the #project alias resolves to nothing inside the container"
        )

    def test_they_are_mounted_as_siblings(self):
        """The relative paths on both sides depend on the shared parent, so
        mounting them anywhere unrelated resolves the alias and breaks the
        project's imports map instead."""
        service = self._frontend_build()
        targets = {m.split(":")[0]: m.split(":")[1] for m in service["volumes"] if m.startswith("./")}
        frontend = targets["./frontend"]
        projects = targets["./projects"]
        assert frontend.rsplit("/", 1)[0] == projects.rsplit("/", 1)[0], (
            f"frontend is at {frontend} and projects at {projects}; they must share a parent directory"
        )

    def test_the_working_directory_is_the_mounted_frontend(self):
        service = self._frontend_build()
        targets = {m.split(":")[0]: m.split(":")[1] for m in service["volumes"] if m.startswith("./")}
        assert service["working_dir"] == targets["./frontend"], (
            "working_dir does not point at where frontend/ is mounted"
        )

    def test_the_projects_mount_is_writable(self):
        """The frontend postinstall symlinks node_modules into each project
        frontend; a read-only mount fails the install rather than the build."""
        for mount in self._frontend_build()["volumes"]:
            if mount.startswith("./projects"):
                assert not mount.endswith(":ro"), "projects/ is mounted read-only, so link:projects cannot run"
